model:
  name: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  max_length: 512
  padding: "max_length"
  truncation: true
  use_4bit: true

training:
  output_dir: "model/checkpoints"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_steps: 100
  logging_steps: 10
  save_steps: 50
  evaluation_strategy: "steps"
  eval_steps: 50
  load_best_model_at_end: true
  metric_for_best_model: "loss"
  greater_is_better: false
  fp16: true
  max_length: 512

lora:
  r: 16
  alpha: 32
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
  dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
